Add Question 1 Page card (#40)
BobaTalks/pick-a-major pull request #72
Opened 2023-03-20 21:19 UTC by jshiii117

## Description
#### What is the purpose of your change?
- Adding new component

#### What areas of the application does this change impact? (changes API, folder structure, etc)
- Changes frontend

#### What features/fixes are deferred/not handled in this PR?
- Does not include parent container for holding individual cards

## Checklist
- [ ] Adds unit tests
- [X] Has a work item linked to the PR

2023-03-20 21:33 UTC, jwu910 requested changes
left some comments, will like to see some changes made.

If you can also provide some screenshots or gifs of the component as it is, that would be helpful to preview the work, looking forward to the next review

2023-03-20 21:33 UTC, jwu910 commented on tmt-app/src/Components/QuestionCard.js
can we use `jsx` for extensions for files with jsx in it? helps distinguish between javascript files and files with react jsx code. Ideally we can use util files or helper files with `.js` endings to indicate its mostly just plain javascript in that file, `.jsx` makes it easier to tell that this file is a component

2023-03-20 21:33 UTC, jwu910 commented on tmt-app/src/Components/QuestionCard.js
> +      style={style}
we should consider using the `sx` prop over `style` when possible https://mui.com/system/getting-started/the-sx-prop/

2023-03-20 21:33 UTC, jwu910 commented on tmt-app/src/Components/QuestionCard.js
> +        <>
The Grid parent item may or may not be helpful. we had mentioned over the call that the grid might be too rigid for something like this as working with flex and auto wrapping elements at the responsibility of the browser would probably be less work for us.

Lets take that into consideration, if the parent is no longer Grid, do we want a Fragment here, or do we want another MUI element we could add some styles to?

2023-03-21 03:45 UTC, jshiii117 commented on tmt-app/src/Components/QuestionCard.js
> +    border: isSelected
Thanks for reviewing the changes Josh! Just a bit confused by this one, what is meant by sorting the objects?

2023-03-22 01:14 UTC, jwu910 commented on tmt-app/src/Components/QuestionCard.jsx
> +      style={sx}
Fyi, using a variable named `sx` won't be the same as using the `sx` prop available through MUI components https://mui.com/system/getting-started/the-sx-prop/

2023-03-24 03:00 UTC, michachan approved these changes
Awesome, looks good to me!

2023-03-24 04:55 UTC, jwu910 approved these changes

2023-03-24 04:56 UTC, merged