Majors Cards (Fixes #42)
BobaTalks/pick-a-major pull request #95
Opened 2023-04-12 01:39 UTC by jshiii117

## Description
#### What is the purpose of your change?
- Adding access to new Questions page and Grid container for individual major cards

#### What areas of the application does this change impact? (changes API, folder structure, etc)
- Added new file
- Minor change to routes in App.js

#### What features/fixes are deferred/not handled in this PR?
- Not yet added other page routes (will come in separate PR)

## Checklist
- [ ] Adds unit tests
- [X] Has a work item linked to the PR

![image](https://user-images.githubusercontent.com/74488095/231325063-e623c854-25ad-4f69-a243-44829ce6cbc3.png)

2023-04-12 18:57 UTC, jwu910 requested changes

2023-04-12 18:57 UTC, jwu910 commented on tmt-app/src/Components/Questions.jsx
> +const TEST_ITEMS = [
Same feedback Ive left for Raymond, let's export this from a mock data file so we can clean up the components we're actually importing them from

2023-04-12 18:58 UTC, jwu910 commented
Build is failing, please review checks to ensure passing build

2023-04-24 17:59 UTC, jwu910 commented
@jshiii117 gonna have to resolve conflicts here before we can move forward with this fyi, raymond just merged in the big PR

CC: @Brian-Miki @kpxwinter

2023-04-25 16:34 UTC, michachan approved these changes

2023-04-25 16:35 UTC, merged